### ISSUE TITLE
redundant model/task in qa folder

### ISSUE THREAD

**Issue by gciccarelli3** [gablab/openfmri#9]
/om/project/voice/processedData/l1analysis/l1output_20160901a/model124/task005/sub-voice850/qa/mask/model124/task005

**Comment by gciccarelli3** [comment]
also in tsnr folder

/om/project/voice/processedData/l1analysis/l1output_20160901a/model124/task005/sub-voice850/qa/tsnr/model124/task005

I'll submit a pull request if I figure out how to fix- unless this is not a bug?

**Comment by mgxd** [comment]
this probably has to do with #4 - we could add in

```
subs.append(('mask/model%03d/task%03d/' % (model_id, task_id), 'mask/'))
subs.append(('tsnr/model%03d/task%03d/' % (model_id, task_id), 'tsnr/'))
```

and it should fix it.
